name: Codecoverage

push: {branches: master}
pull_request: {branches: master}

jobs:
  codecov:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.9.4
      - run: mix deps.get
      - run: MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)
